import { Event } from "./types";

const mockEvents: Event[] = [
  // --- San Francisco, CA ---
  {
    id: 1,
    organization_id: 1,
    title: "Annual Tech Conference",
    description: "A full-day conference featuring keynotes and workshops on the latest trends in software development, AI, and cloud computing.",
    start_time: "2026-04-10 09:00:00",
    end_time: "2026-04-10 18:00:00",
    address: "Moscone Center, San Francisco, CA",
    address_details: "Hall B — Main Stage entrance on Howard St",
    lat: 37.7841,
    lng: -122.4006,
    max_capacity: 500,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Tech"],
  },
  {
    id: 12,
    organization_id: 4,
    title: "Holiday Craft Fair",
    description: "Over 80 local vendors selling handmade goods, artwork, and holiday gifts. Live carolers and complimentary hot cocoa.",
    start_time: "2025-12-13 10:00:00",
    end_time: "2025-12-13 18:00:00",
    address: "Union Square, San Francisco, CA",
    lat: 37.7879,
    lng: -122.4075,
    max_capacity: 2000,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Art", "Parties"],
  },
  {
    id: 21,
    organization_id: 2,
    title: "Golden Gate Sunrise Hike",
    description: "A guided sunrise hike across the Golden Gate Bridge followed by a group breakfast at a nearby café.",
    start_time: "2026-05-03 05:30:00",
    end_time: "2026-05-03 09:00:00",
    address: "Golden Gate Bridge, San Francisco, CA",
    address_details: "Meet at the Welcome Center parking lot",
    lat: 37.8199,
    lng: -122.4783,
    max_capacity: 40,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Outdoor"],
  },

  // --- Austin, TX ---
  {
    id: 2,
    organization_id: 2,
    title: "Community Art Walk",
    description: "An evening stroll through downtown galleries showcasing local artists. Light refreshments provided at each venue.",
    start_time: "2026-04-18 17:00:00",
    end_time: "2026-04-18 21:00:00",
    address: "East 6th Street Arts District, Austin, TX",
    lat: 30.2676,
    lng: -97.7301,
    max_capacity: 200,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Art"],
  },
  {
    id: 14,
    organization_id: 2,
    title: "Film Screening: Indie Shorts Festival",
    description: "A curated evening of short films from emerging independent filmmakers. Q&A session with directors after the screening.",
    start_time: "2026-01-17 19:00:00",
    end_time: "2026-01-17 22:30:00",
    address: "Alamo Drafthouse Cinema, Austin, TX",
    address_details: "South Lamar location — Theater 3",
    lat: 30.2500,
    lng: -97.7670,
    max_capacity: 180,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Art"],
  },
  {
    id: 22,
    organization_id: 3,
    title: "Barton Springs Open Water Swim",
    description: "A timed open-water swim event at the iconic Barton Springs Pool. All levels welcome — competitive and casual lanes available.",
    start_time: "2026-06-14 07:00:00",
    end_time: "2026-06-14 11:00:00",
    address: "Barton Springs Pool, Austin, TX",
    lat: 30.2640,
    lng: -97.7710,
    max_capacity: 150,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Sports", "Outdoor"],
  },

  // --- New York, NY ---
  {
    id: 3,
    organization_id: 1,
    title: "Startup Pitch Night",
    description: "Watch 10 early-stage startups pitch their ideas to a panel of investors. Networking reception to follow.",
    start_time: "2026-05-02 18:30:00",
    end_time: "2026-05-02 21:30:00",
    address: "WeWork 5th Avenue, New York, NY",
    address_details: "Floor 12 — Rooftop event space",
    lat: 40.7548,
    lng: -73.9848,
    max_capacity: 150,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Tech"],
  },
  {
    id: 17,
    organization_id: 1,
    title: "Product Design Bootcamp",
    description: "An intensive two-day bootcamp covering UX research, wireframing, prototyping, and user testing. Taught by senior designers from top tech companies.",
    start_time: "2026-02-21 09:00:00",
    end_time: "2026-02-22 17:00:00",
    address: "IDEO Studio, New York, NY",
    address_details: "151 W 26th St, 12th Floor",
    lat: 40.7455,
    lng: -73.9934,
    max_capacity: 50,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Tech", "Art"],
  },
  {
    id: 23,
    organization_id: 4,
    title: "Central Park Jazz Picnic",
    description: "Bring a blanket and enjoy live jazz performances scattered throughout the park. Food trucks and pop-up bars on site.",
    start_time: "2026-07-12 14:00:00",
    end_time: "2026-07-12 20:00:00",
    address: "Central Park, New York, NY",
    address_details: "Sheep Meadow — enter at 66th St & Central Park West",
    lat: 40.7736,
    lng: -73.9743,
    max_capacity: 2000,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Music", "Outdoor"],
  },
  {
    id: 13,
    organization_id: 1,
    title: "New Year's Eve Gala",
    description: "Ring in 2026 with a black-tie dinner, live orchestra, open bar, and a midnight champagne toast overlooking the city skyline.",
    start_time: "2025-12-31 20:00:00",
    end_time: "2026-01-01 01:00:00",
    address: "The Ritz-Carlton New York, Central Park",
    address_details: "50 Central Park South — Grand Ballroom",
    lat: 40.7658,
    lng: -73.9790,
    max_capacity: 350,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Parties", "Music"],
  },

  // --- Chicago, IL ---
  {
    id: 4,
    organization_id: 3,
    title: "5K Charity Run",
    description: "Lace up your shoes and run for a cause! All proceeds go toward local food bank initiatives. Medals for all finishers.",
    start_time: "2026-05-15 07:00:00",
    end_time: "2026-05-15 11:00:00",
    address: "Riverside Park, Chicago, IL",
    address_details: "Start line at the N Riverside Park Mall entrance",
    lat: 41.8412,
    lng: -87.8243,
    max_capacity: 1000,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Sports", "Outdoor"],
  },
  {
    id: 24,
    organization_id: 2,
    title: "Chicago Deep Dish Cook-Off",
    description: "Eight local restaurants compete for the title of Chicago's best deep dish pizza. Unlimited tasting tickets available at the door.",
    start_time: "2026-08-09 12:00:00",
    end_time: "2026-08-09 17:00:00",
    address: "Millennium Park, Chicago, IL",
    address_details: "Jay Pritzker Pavilion lawn",
    lat: 41.8826,
    lng: -87.6226,
    max_capacity: 1500,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Food & Drink"],
  },
  {
    id: 25,
    organization_id: 3,
    title: "Improv Comedy Showcase",
    description: "Six of Chicago's best improv troupes take the stage for a laugh-packed evening of unscripted comedy.",
    start_time: "2026-04-25 20:00:00",
    end_time: "2026-04-25 23:00:00",
    address: "Second City, Chicago, IL",
    address_details: "1616 N Wells St — Mainstage",
    lat: 41.9130,
    lng: -87.6348,
    max_capacity: 320,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Parties"],
  },

  // --- Seattle, WA ---
  {
    id: 5,
    organization_id: 2,
    title: "Cooking Masterclass: Italian Cuisine",
    description: "Join Chef Marco Russo for a hands-on cooking class covering pasta, risotto, and tiramisu. All ingredients included.",
    start_time: "2026-05-22 14:00:00",
    end_time: "2026-05-22 17:00:00",
    address: "The Culinary Studio, Seattle, WA",
    address_details: "2716 1st Ave — Studio Kitchen on 2nd floor",
    lat: 47.6128,
    lng: -122.3530,
    max_capacity: 24,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Food & Drink"],
  },
  {
    id: 18,
    organization_id: 2,
    title: "Open Mic Night",
    description: "A welcoming stage for musicians, comedians, poets, and spoken word artists. Sign up at the door. All genres and skill levels encouraged.",
    start_time: "2026-03-06 20:00:00",
    end_time: "2026-03-06 23:00:00",
    address: "The Velvet Lounge, Seattle, WA",
    address_details: "915 E Pine St",
    lat: 47.6148,
    lng: -122.3199,
    max_capacity: 90,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Music"],
  },
  {
    id: 26,
    organization_id: 1,
    title: "Pike Place Market Food Tour",
    description: "A guided two-hour tasting tour through Pike Place Market featuring local vendors, seafood, and artisan cheeses.",
    start_time: "2026-06-27 11:00:00",
    end_time: "2026-06-27 13:00:00",
    address: "Pike Place Market, Seattle, WA",
    address_details: "Meet at the main Market sign — Pike St & 1st Ave",
    lat: 47.6085,
    lng: -122.3406,
    max_capacity: 20,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Food & Drink", "Outdoor"],
  },

  // --- Nashville, TN ---
  {
    id: 6,
    organization_id: 4,
    title: "Jazz in the Park",
    description: "An outdoor evening concert featuring three local jazz bands. Bring a blanket, grab a drink, and enjoy the music under the stars.",
    start_time: "2026-06-06 19:00:00",
    end_time: "2026-06-06 23:00:00",
    address: "Centennial Park, Nashville, TN",
    address_details: "Bandshell stage near the Parthenon replica",
    lat: 36.1493,
    lng: -86.8139,
    max_capacity: 800,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Music", "Outdoor"],
  },
  {
    id: 16,
    organization_id: 4,
    title: "Valentine's Trivia Night",
    description: "Grab your partner or your friends for a fun evening of themed trivia. Cash prizes for first and second place. No registration required.",
    start_time: "2026-02-14 19:00:00",
    end_time: "2026-02-14 22:00:00",
    address: "The Taproom Broadway, Nashville, TN",
    address_details: "110 Broadway — upstairs bar",
    lat: 36.1600,
    lng: -86.7785,
    max_capacity: 100,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Parties"],
  },
  {
    id: 27,
    organization_id: 3,
    title: "Country Music Songwriter Circle",
    description: "An intimate evening with four Nashville songwriters performing originals and sharing the stories behind them.",
    start_time: "2026-05-30 19:30:00",
    end_time: "2026-05-30 22:00:00",
    address: "The Bluebird Cafe, Nashville, TN",
    lat: 36.1100,
    lng: -86.8097,
    max_capacity: 90,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Music"],
  },

  // --- Portland, OR ---
  {
    id: 7,
    organization_id: 3,
    title: "Photography Workshop",
    description: "A beginner-friendly workshop covering composition, lighting, and editing techniques. Bring your own camera or smartphone.",
    start_time: "2026-06-13 10:00:00",
    end_time: "2026-06-13 14:00:00",
    address: "The Photo Loft, Portland, OR",
    address_details: "537 SE Ash St — Suite 201",
    lat: 45.5201,
    lng: -122.6580,
    max_capacity: 30,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Art"],
  },
  {
    id: 15,
    organization_id: 3,
    title: "Urban Gardening Workshop",
    description: "Learn how to grow herbs, vegetables, and flowers in small urban spaces. Take home a starter kit with seeds and a planter.",
    start_time: "2026-02-07 10:00:00",
    end_time: "2026-02-07 13:00:00",
    address: "Green Thumb Community Center, Portland, OR",
    address_details: "1600 NE Alberta St",
    lat: 45.5582,
    lng: -122.6480,
    max_capacity: 40,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Outdoor"],
  },
  {
    id: 28,
    organization_id: 4,
    title: "Portland Night Market",
    description: "A vibrant night market featuring 60+ local food vendors, craft beverages, live music, and handmade goods.",
    start_time: "2026-07-18 17:00:00",
    end_time: "2026-07-18 23:00:00",
    address: "Tom McCall Waterfront Park, Portland, OR",
    lat: 45.5165,
    lng: -122.6768,
    max_capacity: 3000,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Food & Drink", "Music", "Outdoor"],
  },

  // --- Denver, CO ---
  {
    id: 8,
    organization_id: 4,
    title: "Board Game Bonanza",
    description: "An afternoon of strategy, luck, and fun! Over 200 board games available to play. Snacks and non-alcoholic beverages included.",
    start_time: "2026-06-20 12:00:00",
    end_time: "2026-06-20 20:00:00",
    address: "The Game Vault, Denver, CO",
    address_details: "2843 Larimer St",
    lat: 39.7577,
    lng: -104.9781,
    max_capacity: 120,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Parties"],
  },
  {
    id: 19,
    organization_id: 3,
    title: "Mindfulness & Meditation Seminar",
    description: "A Saturday morning seminar on stress reduction, mindful breathing, and building a daily meditation practice. Mats and materials provided.",
    start_time: "2026-03-07 09:00:00",
    end_time: "2026-03-07 12:00:00",
    address: "Serenity Wellness Center, Denver, CO",
    address_details: "1600 Glenarm Pl — 3rd floor",
    lat: 39.7453,
    lng: -104.9905,
    max_capacity: 45,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Outdoor"],
  },
  {
    id: 29,
    organization_id: 1,
    title: "Rocky Mountain Trail Run",
    description: "A scenic 10-mile trail run through Rocky Mountain National Park. Shuttle provided from downtown Denver.",
    start_time: "2026-08-22 07:00:00",
    end_time: "2026-08-22 14:00:00",
    address: "Rocky Mountain National Park, Estes Park, CO",
    address_details: "Bear Lake Trailhead",
    lat: 40.3129,
    lng: -105.6481,
    max_capacity: 200,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Sports", "Outdoor"],
  },

  // --- Boston, MA ---
  {
    id: 9,
    organization_id: 1,
    title: "Women in Leadership Summit",
    description: "A half-day summit celebrating and empowering women in leadership roles with panel discussions, networking, and workshops.",
    start_time: "2026-07-08 08:30:00",
    end_time: "2026-07-08 13:00:00",
    address: "Grand Hyatt Boston, Boston, MA",
    address_details: "One Avenue de Lafayette — Harbor Ballroom",
    lat: 42.3543,
    lng: -71.0623,
    max_capacity: 300,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Tech"],
  },
  {
    id: 11,
    organization_id: 3,
    title: "Winter Hackathon 2025",
    description: "A 24-hour hackathon where teams of up to four competed to build innovative solutions to real-world problems. Prizes awarded in three categories.",
    start_time: "2025-12-06 09:00:00",
    end_time: "2025-12-07 09:00:00",
    address: "MIT Media Lab, Cambridge, MA",
    address_details: "75 Amherst St — E14 Building, 6th floor",
    lat: 42.3601,
    lng: -71.0872,
    max_capacity: 200,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Tech"],
  },
  {
    id: 30,
    organization_id: 2,
    title: "Freedom Trail History Walk",
    description: "A guided 2.5-mile walk along Boston's Freedom Trail with a professional historian. Ends with drinks at a colonial-era tavern.",
    start_time: "2026-05-09 10:00:00",
    end_time: "2026-05-09 13:00:00",
    address: "Boston Common, Boston, MA",
    address_details: "Meet at the Visitor Information Center near Tremont St",
    lat: 42.3554,
    lng: -71.0655,
    max_capacity: 35,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Outdoor"],
  },

  // --- Asheville, NC ---
  {
    id: 10,
    organization_id: 2,
    title: "Outdoor Yoga Retreat",
    description: "A rejuvenating full-day yoga retreat in the mountains. All skill levels welcome. Includes guided meditation and a healthy lunch.",
    start_time: "2026-07-19 08:00:00",
    end_time: "2026-07-19 16:00:00",
    address: "Blue Ridge Parkway, Asheville, NC",
    address_details: "Craggy Gardens Picnic Area — milepost 364",
    lat: 35.6815,
    lng: -82.3918,
    max_capacity: 60,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Outdoor"],
  },

  // --- Madison, WI ---
  {
    id: 20,
    organization_id: 4,
    title: "Early Morning Farmers Market",
    description: "Shop fresh produce, artisan breads, local honey, and handmade goods from over 50 vendors. Live acoustic music and free coffee samples while supplies last.",
    start_time: "2026-03-11 05:00:00",
    end_time: "2026-03-11 11:00:00",
    address: "Capitol Square, Madison, WI",
    lat: 43.0731,
    lng: -89.4012,
    max_capacity: 600,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Food & Drink", "Outdoor"],
  },

  // --- Los Angeles, CA ---
  {
    id: 31,
    organization_id: 1,
    title: "Rooftop Cinema Night",
    description: "Watch a classic film under the stars on a rooftop overlooking the LA skyline. Bring your own blanket; popcorn and drinks provided.",
    start_time: "2026-04-04 20:00:00",
    end_time: "2026-04-04 23:00:00",
    address: "The Rooftop at The Standard, Los Angeles, CA",
    address_details: "550 S Flower St — access via hotel lobby elevator",
    lat: 34.0500,
    lng: -118.2580,
    max_capacity: 120,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Art", "Parties"],
  },
  {
    id: 32,
    organization_id: 3,
    title: "Venice Beach Volleyball Tournament",
    description: "A doubles volleyball tournament on the sands of Venice Beach. Register solo or as a team. Prizes for top three pairs.",
    start_time: "2026-06-28 09:00:00",
    end_time: "2026-06-28 17:00:00",
    address: "Venice Beach, Los Angeles, CA",
    address_details: "Courts 3–8 near the basketball courts",
    lat: 33.9850,
    lng: -118.4695,
    max_capacity: 128,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Sports", "Outdoor"],
  },
  {
    id: 33,
    organization_id: 2,
    title: "Street Food Festival",
    description: "Thirty food trucks from across LA in one lot. Live DJs, a craft beer garden, and a hot sauce competition.",
    start_time: "2026-05-17 12:00:00",
    end_time: "2026-05-17 21:00:00",
    address: "Grand Park, Los Angeles, CA",
    lat: 34.0563,
    lng: -118.2468,
    max_capacity: 5000,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Food & Drink", "Music"],
  },

  // --- Miami, FL ---
  {
    id: 34,
    organization_id: 4,
    title: "South Beach Art Deco Tour",
    description: "A walking tour of Miami's iconic Art Deco Historic District led by a licensed architectural guide.",
    start_time: "2026-04-11 09:30:00",
    end_time: "2026-04-11 12:00:00",
    address: "Art Deco Welcome Center, Miami Beach, FL",
    address_details: "1001 Ocean Dr — meet on the front steps",
    lat: 25.7817,
    lng: -80.1300,
    max_capacity: 25,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Art", "Outdoor"],
  },
  {
    id: 35,
    organization_id: 1,
    title: "Latin Music Block Party",
    description: "Three stages, twelve acts, and non-stop dancing. Celebrate Latin culture with food, music, and community.",
    start_time: "2026-07-25 16:00:00",
    end_time: "2026-07-25 23:59:00",
    address: "Calle Ocho, Miami, FL",
    address_details: "SW 8th St between 12th and 27th Ave",
    lat: 25.7659,
    lng: -80.2264,
    max_capacity: 10000,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Music", "Parties"],
  },

  // --- Atlanta, GA ---
  {
    id: 36,
    organization_id: 2,
    title: "BeltLine Art Crawl",
    description: "Explore murals, pop-up galleries, and live painting sessions along the Atlanta BeltLine's Eastside Trail.",
    start_time: "2026-05-08 14:00:00",
    end_time: "2026-05-08 20:00:00",
    address: "Ponce City Market, Atlanta, GA",
    address_details: "675 Ponce De Leon Ave NE — start at the BeltLine entrance",
    lat: 33.7721,
    lng: -84.3660,
    max_capacity: 400,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Art", "Outdoor"],
  },
  {
    id: 37,
    organization_id: 3,
    title: "Atlanta BBQ Championship",
    description: "Pitmaster teams from across the Southeast compete for bragging rights. Unlimited tasting wristbands available.",
    start_time: "2026-08-01 11:00:00",
    end_time: "2026-08-01 19:00:00",
    address: "Piedmont Park, Atlanta, GA",
    lat: 33.7874,
    lng: -84.3733,
    max_capacity: 2500,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Food & Drink", "Outdoor"],
  },

  // --- Phoenix, AZ ---
  {
    id: 38,
    organization_id: 4,
    title: "Desert Stargazing Night",
    description: "A guided stargazing event in the Sonoran Desert with telescopes provided. Expert astronomers on hand to answer questions.",
    start_time: "2026-04-17 20:00:00",
    end_time: "2026-04-17 23:30:00",
    address: "McDowell Sonoran Preserve, Scottsdale, AZ",
    address_details: "Ringtail Ridge Trailhead parking lot",
    lat: 33.6839,
    lng: -111.8025,
    max_capacity: 75,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Outdoor"],
  },

  // --- Minneapolis, MN ---
  {
    id: 39,
    organization_id: 1,
    title: "Craft Beer & Code Hackathon",
    description: "A weekend hackathon hosted by the Twin Cities tech community. Prizes in five categories, local craft beers on tap throughout.",
    start_time: "2026-09-12 10:00:00",
    end_time: "2026-09-13 18:00:00",
    address: "Target Field, Minneapolis, MN",
    address_details: "Gate 34 — Innovation Hub entrance",
    lat: 44.9817,
    lng: -93.2782,
    max_capacity: 350,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Tech"],
  },

  // --- New Orleans, LA ---
  {
    id: 40,
    organization_id: 2,
    title: "French Quarter Jazz Brunch",
    description: "A two-hour live jazz brunch in the heart of the French Quarter. Bottomless mimosas and a full Creole brunch menu.",
    start_time: "2026-05-24 10:30:00",
    end_time: "2026-05-24 13:00:00",
    address: "Brennan's Restaurant, New Orleans, LA",
    address_details: "417 Royal St — Courtyard seating",
    lat: 29.9574,
    lng: -90.0644,
    max_capacity: 80,
    image_url: "/mock-event-assets/mockImage.jpg",
    tags: ["Food & Drink", "Music"],
  },
];

export const getEvents = async () => {
  return mockEvents;
};
