import { Event } from "./types";

const mockEvents: Event[] = [
  {
    id: 1,
    organization_id: 1,
    title: "Annual Tech Conference",
    description: "A full-day conference featuring keynotes and workshops on the latest trends in software development, AI, and cloud computing.",
    start_time: "2026-04-10 09:00:00",
    end_time: "2026-04-10 18:00:00",
    location: "Convention Center, San Francisco, CA",
    max_capacity: 500,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 2,
    organization_id: 2,
    title: "Community Art Walk",
    description: "An evening stroll through downtown galleries showcasing local artists. Light refreshments provided at each venue.",
    start_time: "2026-04-18 17:00:00",
    end_time: "2026-04-18 21:00:00",
    location: "Downtown Arts District, Austin, TX",
    max_capacity: 200,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 3,
    organization_id: 1,
    title: "Startup Pitch Night",
    description: "Watch 10 early-stage startups pitch their ideas to a panel of investors. Networking reception to follow.",
    start_time: "2026-05-02 18:30:00",
    end_time: "2026-05-02 21:30:00",
    location: "WeWork Headquarters, New York, NY",
    max_capacity: 150,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 4,
    organization_id: 3,
    title: "5K Charity Run",
    description: "Lace up your shoes and run for a cause! All proceeds go toward local food bank initiatives. Medals for all finishers.",
    start_time: "2026-05-15 07:00:00",
    end_time: "2026-05-15 11:00:00",
    location: "Riverside Park, Chicago, IL",
    max_capacity: 1000,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 5,
    organization_id: 2,
    title: "Cooking Masterclass: Italian Cuisine",
    description: "Join Chef Marco Russo for a hands-on cooking class covering pasta, risotto, and tiramisu. All ingredients included.",
    start_time: "2026-05-22 14:00:00",
    end_time: "2026-05-22 17:00:00",
    location: "The Culinary Studio, Seattle, WA",
    max_capacity: 24,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 6,
    organization_id: 4,
    title: "Jazz in the Park",
    description: "An outdoor evening concert featuring three local jazz bands. Bring a blanket, grab a drink, and enjoy the music under the stars.",
    start_time: "2026-06-06 19:00:00",
    end_time: "2026-06-06 23:00:00",
    location: "Centennial Park, Nashville, TN",
    max_capacity: 800,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 7,
    organization_id: 3,
    title: "Photography Workshop",
    description: "A beginner-friendly workshop covering composition, lighting, and editing techniques. Bring your own camera or smartphone.",
    start_time: "2026-06-13 10:00:00",
    end_time: "2026-06-13 14:00:00",
    location: "The Photo Loft, Portland, OR",
    max_capacity: 30,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 8,
    organization_id: 4,
    title: "Board Game Bonanza",
    description: "An afternoon of strategy, luck, and fun! Over 200 board games available to play. Snacks and non-alcoholic beverages included.",
    start_time: "2026-06-20 12:00:00",
    end_time: "2026-06-20 20:00:00",
    location: "The Game Vault, Denver, CO",
    max_capacity: 120,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 9,
    organization_id: 1,
    title: "Women in Leadership Summit",
    description: "A half-day summit celebrating and empowering women in leadership roles with panel discussions, networking, and workshops.",
    start_time: "2026-07-08 08:30:00",
    end_time: "2026-07-08 13:00:00",
    location: "Grand Hyatt, Boston, MA",
    max_capacity: 300,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 10,
    organization_id: 2,
    title: "Outdoor Yoga Retreat",
    description: "A rejuvenating full-day yoga retreat in the mountains. All skill levels welcome. Includes guided meditation and a healthy lunch.",
    start_time: "2026-07-19 08:00:00",
    end_time: "2026-07-19 16:00:00",
    location: "Blue Ridge Mountain Retreat, Asheville, NC",
    max_capacity: 60,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  // Ongoing event
  {
    id: 20,
    organization_id: 4,
    title: "Early Morning Farmers Market",
    description: "Shop fresh produce, artisan breads, local honey, and handmade goods from over 50 vendors. Live acoustic music and free coffee samples while supplies last.",
    start_time: "2026-03-11 05:00:00",
    end_time: "2026-03-11 11:00:00",
    location: "Capitol Square, Madison, WI",
    max_capacity: 600,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  // Past events
  {
    id: 11,
    organization_id: 3,
    title: "Winter Hackathon 2025",
    description: "A 24-hour hackathon where teams of up to four competed to build innovative solutions to real-world problems. Prizes awarded in three categories.",
    start_time: "2025-12-06 09:00:00",
    end_time: "2025-12-07 09:00:00",
    location: "MIT Media Lab, Cambridge, MA",
    max_capacity: 200,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 12,
    organization_id: 4,
    title: "Holiday Craft Fair",
    description: "Over 80 local vendors selling handmade goods, artwork, and holiday gifts. Live carolers and complimentary hot cocoa.",
    start_time: "2025-12-13 10:00:00",
    end_time: "2025-12-13 18:00:00",
    location: "Union Square, San Francisco, CA",
    max_capacity: 2000,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 13,
    organization_id: 1,
    title: "New Year's Eve Gala",
    description: "Ring in 2026 with a black-tie dinner, live orchestra, open bar, and a midnight champagne toast overlooking the city skyline.",
    start_time: "2025-12-31 20:00:00",
    end_time: "2026-01-01 01:00:00",
    location: "The Ritz-Carlton, Chicago, IL",
    max_capacity: 350,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 14,
    organization_id: 2,
    title: "Film Screening: Indie Shorts Festival",
    description: "A curated evening of short films from emerging independent filmmakers. Q&A session with directors after the screening.",
    start_time: "2026-01-17 19:00:00",
    end_time: "2026-01-17 22:30:00",
    location: "Alamo Drafthouse, Austin, TX",
    max_capacity: 180,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 15,
    organization_id: 3,
    title: "Urban Gardening Workshop",
    description: "Learn how to grow herbs, vegetables, and flowers in small urban spaces. Take home a starter kit with seeds and a planter.",
    start_time: "2026-02-07 10:00:00",
    end_time: "2026-02-07 13:00:00",
    location: "Green Thumb Community Center, Portland, OR",
    max_capacity: 40,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 16,
    organization_id: 4,
    title: "Valentine's Trivia Night",
    description: "Grab your partner or your friends for a fun evening of themed trivia. Cash prizes for first and second place. No registration required.",
    start_time: "2026-02-14 19:00:00",
    end_time: "2026-02-14 22:00:00",
    location: "The Taproom, Nashville, TN",
    max_capacity: 100,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 17,
    organization_id: 1,
    title: "Product Design Bootcamp",
    description: "An intensive two-day bootcamp covering UX research, wireframing, prototyping, and user testing. Taught by senior designers from top tech companies.",
    start_time: "2026-02-21 09:00:00",
    end_time: "2026-02-22 17:00:00",
    location: "IDEO Studio, New York, NY",
    max_capacity: 50,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 18,
    organization_id: 2,
    title: "Open Mic Night",
    description: "A welcoming stage for musicians, comedians, poets, and spoken word artists. Sign up at the door. All genres and skill levels encouraged.",
    start_time: "2026-03-06 20:00:00",
    end_time: "2026-03-06 23:00:00",
    location: "The Velvet Lounge, Seattle, WA",
    max_capacity: 90,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
  {
    id: 19,
    organization_id: 3,
    title: "Mindfulness & Meditation Seminar",
    description: "A Saturday morning seminar on stress reduction, mindful breathing, and building a daily meditation practice. Mats and materials provided.",
    start_time: "2026-03-07 09:00:00",
    end_time: "2026-03-07 12:00:00",
    location: "Serenity Wellness Center, Denver, CO",
    max_capacity: 45,
    image_url: "/mock-event-assets/mockImage.jpg",
  },
]

export const getEvents = async () => {
  return mockEvents;
}
